/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommentsCreateNestedManyWithoutMealsItemsInput } from "./CommentsCreateNestedManyWithoutMealsItemsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  Min,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { LikesCreateNestedManyWithoutMealsItemsInput } from "./LikesCreateNestedManyWithoutMealsItemsInput";
import { PaymentsCreateNestedManyWithoutMealsItemsInput } from "./PaymentsCreateNestedManyWithoutMealsItemsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class MealsCreateInput {
  @ApiProperty({
    required: false,
    type: () => CommentsCreateNestedManyWithoutMealsItemsInput,
  })
  @ValidateNested()
  @Type(() => CommentsCreateNestedManyWithoutMealsItemsInput)
  @IsOptional()
  @Field(() => CommentsCreateNestedManyWithoutMealsItemsInput, {
    nullable: true,
  })
  commentsItems?: CommentsCreateNestedManyWithoutMealsItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  ingredients?: string | null;

  @ApiProperty({
    required: false,
    type: () => LikesCreateNestedManyWithoutMealsItemsInput,
  })
  @ValidateNested()
  @Type(() => LikesCreateNestedManyWithoutMealsItemsInput)
  @IsOptional()
  @Field(() => LikesCreateNestedManyWithoutMealsItemsInput, {
    nullable: true,
  })
  likesItems?: LikesCreateNestedManyWithoutMealsItemsInput;

  @ApiProperty({
    required: false,
    type: () => PaymentsCreateNestedManyWithoutMealsItemsInput,
  })
  @ValidateNested()
  @Type(() => PaymentsCreateNestedManyWithoutMealsItemsInput)
  @IsOptional()
  @Field(() => PaymentsCreateNestedManyWithoutMealsItemsInput, {
    nullable: true,
  })
  paymentsItems?: PaymentsCreateNestedManyWithoutMealsItemsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { MealsCreateInput as MealsCreateInput };
