/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommentsUpdateManyWithoutMealsItemsInput } from "./CommentsUpdateManyWithoutMealsItemsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  Min,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { LikesUpdateManyWithoutMealsItemsInput } from "./LikesUpdateManyWithoutMealsItemsInput";
import { PaymentsUpdateManyWithoutMealsItemsInput } from "./PaymentsUpdateManyWithoutMealsItemsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class MealsUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CommentsUpdateManyWithoutMealsItemsInput,
  })
  @ValidateNested()
  @Type(() => CommentsUpdateManyWithoutMealsItemsInput)
  @IsOptional()
  @Field(() => CommentsUpdateManyWithoutMealsItemsInput, {
    nullable: true,
  })
  commentsItems?: CommentsUpdateManyWithoutMealsItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  ingredients?: string | null;

  @ApiProperty({
    required: false,
    type: () => LikesUpdateManyWithoutMealsItemsInput,
  })
  @ValidateNested()
  @Type(() => LikesUpdateManyWithoutMealsItemsInput)
  @IsOptional()
  @Field(() => LikesUpdateManyWithoutMealsItemsInput, {
    nullable: true,
  })
  likesItems?: LikesUpdateManyWithoutMealsItemsInput;

  @ApiProperty({
    required: false,
    type: () => PaymentsUpdateManyWithoutMealsItemsInput,
  })
  @ValidateNested()
  @Type(() => PaymentsUpdateManyWithoutMealsItemsInput)
  @IsOptional()
  @Field(() => PaymentsUpdateManyWithoutMealsItemsInput, {
    nullable: true,
  })
  paymentsItems?: PaymentsUpdateManyWithoutMealsItemsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { MealsUpdateInput as MealsUpdateInput };
