/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommentsListRelationFilter } from "../../comments/base/CommentsListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { LikesListRelationFilter } from "../../likes/base/LikesListRelationFilter";
import { PaymentsListRelationFilter } from "../../payments/base/PaymentsListRelationFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class MealsWhereInput {
  @ApiProperty({
    required: false,
    type: () => CommentsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CommentsListRelationFilter)
  @IsOptional()
  @Field(() => CommentsListRelationFilter, {
    nullable: true,
  })
  commentsItems?: CommentsListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  ingredients?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => LikesListRelationFilter,
  })
  @ValidateNested()
  @Type(() => LikesListRelationFilter)
  @IsOptional()
  @Field(() => LikesListRelationFilter, {
    nullable: true,
  })
  likesItems?: LikesListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PaymentsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PaymentsListRelationFilter)
  @IsOptional()
  @Field(() => PaymentsListRelationFilter, {
    nullable: true,
  })
  paymentsItems?: PaymentsListRelationFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  price?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;
}

export { MealsWhereInput as MealsWhereInput };
