/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommentsCreateNestedManyWithoutUsersInput } from "./CommentsCreateNestedManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { LikesCreateNestedManyWithoutUsersInput } from "./LikesCreateNestedManyWithoutUsersInput";
import { MealsCreateNestedManyWithoutUsersInput } from "./MealsCreateNestedManyWithoutUsersInput";
import { PaymentsCreateNestedManyWithoutUsersInput } from "./PaymentsCreateNestedManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => CommentsCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CommentsCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CommentsCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  commentsItems?: CommentsCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => LikesCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => LikesCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => LikesCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  likesItems?: LikesCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => MealsCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MealsCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MealsCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  mealsItems?: MealsCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => PaymentsCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PaymentsCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PaymentsCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  paymentsItems?: PaymentsCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
