/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PaymentsService } from "../payments.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PaymentsCreateInput } from "./PaymentsCreateInput";
import { Payments } from "./Payments";
import { PaymentsFindManyArgs } from "./PaymentsFindManyArgs";
import { PaymentsWhereUniqueInput } from "./PaymentsWhereUniqueInput";
import { PaymentsUpdateInput } from "./PaymentsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PaymentsControllerBase {
  constructor(
    protected readonly service: PaymentsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Payments })
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPayments(
    @common.Body() data: PaymentsCreateInput
  ): Promise<Payments> {
    return await this.service.createPayments({
      data: {
        ...data,

        meal: data.meal
          ? {
              connect: data.meal,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        amount: true,
        createdAt: true,
        id: true,

        meal: {
          select: {
            id: true,
          },
        },

        stripePaymentId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Payments] })
  @ApiNestedQuery(PaymentsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async paymentsItems(@common.Req() request: Request): Promise<Payments[]> {
    const args = plainToClass(PaymentsFindManyArgs, request.query);
    return this.service.paymentsItems({
      ...args,
      select: {
        amount: true,
        createdAt: true,
        id: true,

        meal: {
          select: {
            id: true,
          },
        },

        stripePaymentId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Payments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async payments(
    @common.Param() params: PaymentsWhereUniqueInput
  ): Promise<Payments | null> {
    const result = await this.service.payments({
      where: params,
      select: {
        amount: true,
        createdAt: true,
        id: true,

        meal: {
          select: {
            id: true,
          },
        },

        stripePaymentId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Payments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePayments(
    @common.Param() params: PaymentsWhereUniqueInput,
    @common.Body() data: PaymentsUpdateInput
  ): Promise<Payments | null> {
    try {
      return await this.service.updatePayments({
        where: params,
        data: {
          ...data,

          meal: data.meal
            ? {
                connect: data.meal,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          amount: true,
          createdAt: true,
          id: true,

          meal: {
            select: {
              id: true,
            },
          },

          stripePaymentId: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Payments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Payments",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePayments(
    @common.Param() params: PaymentsWhereUniqueInput
  ): Promise<Payments | null> {
    try {
      return await this.service.deletePayments({
        where: params,
        select: {
          amount: true,
          createdAt: true,
          id: true,

          meal: {
            select: {
              id: true,
            },
          },

          stripePaymentId: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
